server:
  port: 8222

spring:
  datasource:
    username: sa
    password: pass
    url: jdbc:h2:mem:orderTable
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format-sql: true
#For Config service
  profiles:
    active: native #'git' to pick from GIT
  cloud:
    config:
      server:
        native:
          search-location: classpath:/config/orderservice,classpath:/config/orderservice
#        git:
#          uri: git@gitlab.com:classpath-spring-microservices/orderservice.git
#          repos:
#            apigateway:
#              uri: git@gitlab.com:classpath-spring-microservices/apigateway.git
#              clone-on-startup: true

